# fly.toml app configuration file generated for iae-calc on 2024-03-31T11:48:54+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'iae-calc'
primary_region = 'lax'
console_command = '/rails/bin/rails console'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
