service: iae_calc
image: hhassig/iae_calc
servers:
  web:
    hosts:
      - 100.119.170.114
    options:
      publish:
        - "8086:80"
proxy:
  ssl: false
  host: iae-calc.hassig.com
ssh:
  user: harrison

registry:
  server: localhost:5556
env:
  secret:
    - RAILS_MASTER_KEY
    - KAMAL_REGISTRY_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "iae_calc_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
