service: iae_calc
image: hhassig/iae_calc
servers:
  web:
    hosts:
      - 100.90.13.19
    options:
      publish:
        - "8086:80"
    env:
      DB_HOST: iae_calc-db
      SOLID_QUEUE_IN_PUMA: "true"
proxy:
  ssl: true
  host: iae-calc.hassig.com
registry:
  username: hhassig
  password:
    - KAMAL_REGISTRY_PASSWORD
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - IAE_CALC_DATABASE_PASSWORD
    - KAMAL_REGISTRY_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    POSTGRES_USER: iae_calc
    POSTGRES_DB: iae_calc_production
    POSTGRES_HOST: iae_calc-db
    POSTGRES_PORT: 5432
    DB_HOST: iae_calc-db
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "iae_calc_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
accessories:
  db:
    image: postgres:16
    host: 100.90.13.19
    port: 5437:5432
    env:
      secret:
        - POSTGRES_PASSWORD
      clear:
        POSTGRES_USER: iae_calc
        POSTGRES_DB: iae_calc_production
    volumes:
      - /root/iae_calc-db/data:/var/lib/postgresql/data
      - /root/iae_calc-db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
