service: iae_calc
image: hhassig/iae_calc
servers:
  web:
    hosts:
      - 100.97.138.69
    options:
      publish:
        - "8086:80"
    env:
      DB_HOST: iae_calc-db
      SOLID_QUEUE_IN_PUMA: "true"
proxy:
  ssl: false
  host: iae-calc.hassig.com
registry:
  server: localhost:5558
env:
  secret:
    - RAILS_MASTER_KEY
    - POSTGRES_PASSWORD
    - IAE_CALC_DATABASE_PASSWORD
  clear:
    SOLID_QUEUE_IN_PUMA: true
    POSTGRES_USER: iae_calc
    POSTGRES_DB: iae_calc_production
    POSTGRES_HOST: postgres16
    POSTGRES_PORT: 5432
aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole"
volumes:
  - "iae_calc_storage:/rails/storage"
asset_path: /rails/public/assets
builder:
  arch: amd64
